### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by GeoffreyChen777** [AlphaGogoo/paperlib-ccf-rank-scrape-extension#1]
你这样写死之后，有几个问题：

比如：`,{"short_name":"CVPR","full_name":"IEEE\/CVF Computer Vision and\nPattern Recognition Conference","CCF_Rank":"CCF-A"`

首先你得处理一下所有的 full_name, 去掉一下这些换行符之类的东西。

其次你用 `includes()` 这种强匹配，会导致如果论文的 `publication` 和你这个格式不一样的话，就匹配失败。比如，在我这里，CVPR 是 `IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR)` 显然就匹配不到你那个了。

我的建议是，使用 string similarity。https://www.npmjs.com/package/string-similarity

先把所有字符串里面的特殊符号，空格啥的去掉，然后比较similarity，设置一个比较大的阈值。

同时防止有的同学喜欢用short_name，也看一下 `short_name = publication`。这两个判断条件，应该就差不多。

**Comment by GeoffreyChen777** [comment]
大部分计算机领域的论文，在 Paperlib 里都会有 `会议全称（简称）`这样的格式。你可以相应做处理。

**Comment by GeoffreyChen777** [comment]
你也可以检测论文 publication 有没有括号，有的话，直接正则提取括号内内容，那一般就是short name，然后对比shortname就可以了。

**Comment by GeoffreyChen777** [comment]
还有这个

https://github.com/AlphaGogoo/paperlib-ccf-rank-scrape-extension/blob/3d7c581b7789dd4708daa8650331a63f59b24882/src/main.ts#L54

支持 HTML。你可以给不同 rank 上色。

**Comment by Duducoco** [comment]
感谢，我尽快修改

**Comment by GeoffreyChen777** [comment]
作为第一个非官方社区插件，很棒啦！

**Comment by Duducoco** [comment]
目前应该比较准确了，但应该也是会有问题，遇到问题继续修

**Comment by GeoffreyChen777** [comment]
<img width="346" alt="image" src="https://github.com/AlphaGogoo/paperlib-ccf-rank-scrape-extension/assets/14183213/3f3300c1-c170-46bf-af66-88ab2f6cfb00">

大部分准了，但是 ECCV 看一眼， 应该是 CCFB

**Comment by GeoffreyChen777** [comment]
还有建议 package.json 里面加上 homepage 为这个github。当用户有问题的时候，知道来这里反馈。

**Comment by Duducoco** [comment]
已修复

**Comment by GeoffreyChen777** [comment]
ok 可以了。

麻烦问一下，开发过程中，还顺利不，API易用性，文档等方面，有任何建议可以提出来。

**Comment by Duducoco** [comment]
大部分都还算清晰，HelloWorld也比较明白，不过有个地方刚开始有点困惑

比如下面的UI slot，这个id没有写清楚，不知道要写什么合适
<img width="776" alt="image" src="https://github.com/AlphaGogoo/paperlib-ccf-rank-scrape-extension/assets/69681789/3a76887f-e4bd-4f2f-8c38-551ad9830f5b">

**Comment by GeoffreyChen777** [comment]
OK 感谢反馈。
