### ISSUE TITLE
设置tag的颜色

### ISSUE THREAD

**Issue by jiadong825** [AlphaGogoo/paperlib-ccf-rank-scrape-extension#2]
您好，请问可否修改目前tag中字的颜色，目前的配色在个人看来可能较不优雅。可以参考chrome插件 [CCFrank](https://chromewebstore.google.com/detail/ccfrank/pfcajmbenomfbjnbjhgbnbdjmiklnkie)的配色 将字的颜色修改为白色并加粗。亦或是不设置背景颜色。后续可修改为在插件界面自定义字体颜色，字体加粗和背景颜色。

**Comment by Duducoco** [comment]
感谢反馈，尽快处理

**Comment by Duducoco** [comment]
已优化
